added uidtool
zopefoundation/Products.CMFUid pull request #23
Opened 2023-09-20 06:48 UTC by Akshat2Jain

this pr is related to https://github.com/plone/Products.CMFPlone/pull/3836

2023-09-20 12:46 UTC, wesleybl requested changes
I think the commit message should be something like:

"Prevents handleUidAnnotationEvent failure if portal_uidhandler is not available"

Please add an entry to Changes

2023-09-21 21:28 UTC, wesleybl requested changes

2023-09-21 21:28 UTC, wesleybl commented on CHANGES.rst
> +- modified the code to check if both 'anno_tool' and 'uidtool' exist before using them. This change ensures that the code won't run unless both tools are available, preventing the 'NoneType' error.
```suggestion
- Modified the code of ``handleUidAnnotationEvent`` to check if both 'anno_tool' and 'uidtool' exist before using them. This change ensures that the code won't run unless both tools are available, preventing the 'NoneType' error.
```

2023-09-22 13:43 UTC, wesleybl approved these changes

2023-09-22 13:45 UTC, merged

2023-09-22 13:46 UTC, wesleybl commented
@icemac @dataflake can you create a new release please?

2023-10-02 15:00 UTC, dataflake commented
Version 4.1 is now released.

2023-10-02 15:08 UTC, wesleybl commented
> Version 4.1 is now released.

Thanks!